Update cond.js
ramda/ramda pull request #3179
Opened 2021-09-05 12:27 UTC by xp44mm

Attach an argument to the transformer function to pass the result value of the predicate. 
```js
transformer(...arguments, predicate)
```

2021-09-05 20:04 UTC, CrossEye requested changes
Please read our [Contributing][co] document.  It probably needs an update, but it's a start.

  - There are no associated tests for the changes to the `cond` function.
  - There are formatting changes differing from usual Ramda conventions
  - It uses es6 methods, which Ramda has not adopted and will not adopt until afterrsion 1.0
  - There is no explanation or example

That last point is the most important.  *Why* would we want to do this?  What problem does it solve?  It seems to make `cond` a much more complex function.  What are the benefits that outweigh the complexity?

  [co]: https://github.com/ramda/ramda/blob/master/CONTRIBUTING.md

2021-09-06 01:29 UTC, xp44mm commented
I've passed the existing tests, added tests for new features, and passed them.

2021-09-08 02:00 UTC, CrossEye commented
I think we need much more of an explanation of *why*.  I can read the code and see what it does.  But I can't get into your head to understand your rationale.

Can you add to the discussion here, explaining what these changes are for, and why in some real world example we would want this and want to expand `cond` to cover it?

2021-09-08 06:35 UTC, xp44mm commented
The branch of cond is the predicate first, and the tranformer is performed if the predicate is true. 

Moreover, We also often encounter when part of the tranformer execution has even come to fruition to know if the action should be performed. That is, predicate and transformer cannot be separated from each other.

The latter's signature is similar to: `input -> Some result | None`. Common functions includes: `parseInt`, `parseFloat`, `tryXXX`.

2021-09-08 19:21 UTC, CrossEye commented
I would suggest that if you are looking for the behavior of returning the first non-nil result when applying our arguments to a list of functions, then you should probably suggest a new function.  Ramda strives for API simplicity and would never be apt to deal with such different signatures for the same function.

Although this implementation would not be suitable for current Ramda, the idea would be something like this:

```js
const firstTruthy = (fns) => (...args) => {
  for (let fn of fns) {
    const res = fn (...args)
    if (res) {return res}
  }
}

const myFn = firstTruthy ([
  x => x > 20 && x * x,
  x => x % 2 && (x - 1) / 2,
  x => 10 * x
])

myFn (25) //=> 25 * 25 ==> 625
myFn (15) //=> (7 - 1) / 2 ==> 3
myFn (14) //=> 10 * 14 ==> 140
```

We would still need to see some realistic reasoning for this.  I'm not yet convinced of the usefulness of it, but I'm willing to be convinced if you have a compelling argument.

2021-09-08 23:10 UTC, xp44mm commented
The `firstTruthy` may have missed a situation:
```js
    let fmt = cond([
      [trim, (_, res) => ({ res })],
    ]);
```
the transformer will accept the returned value of the predicate as appended last argument.

2021-09-08 23:15 UTC, xp44mm commented
and this code will terminate at the first branch, skip the second branch:
```js
    let fmt = cond([
      [T, always(false)],
      [T, always('never')],
    ]);
```

2021-09-09 01:29 UTC, CrossEye commented
`firstTruthy` was entirely off the cuff.  I'm still trying to understand what your function is *for*.  I simply don't have a real sense of how you'd want to use this.  I'm quite sure that it's not likely a match for `cond`, which has a fairly simple signature and fairly understandable use.  But it's possible that it's something worth considering for Ramda under a different name.  But we seem to be having communication issues.

Do you have a real-world problem that you could simplify for an example?

2021-09-09 01:59 UTC, xp44mm commented
The extended function is similar to pattern matching in F#, instead of `if..else` string. It is still compatible with the latter. However, it provides features similar to active pattern in F#. Here's the pseudocode:

```F#
match inp with
| _ when predicate(inp) as res -> transformer(inp,res)
| TryFloat (floatResult) -> floatResult
```

`tryFloat` is the js build-in function when sucess return a number or failed return null. transpile to js:

```js
cond([
    [predicate, transformer],
    tryFloat,
])(inp)
```

2021-09-09 03:25 UTC, CrossEye commented
None of this looks anything like a real-world example.  Can you describe a use in something like a web application or a data transformation one.  The business domain is not important, just something concrete that shows *why* you want this.

2022-01-21 09:34 UTC, customcommander commented
@CrossEye Shall we close this one for now?

2022-01-22 17:09 UTC, closed without merging