doc: memoizeWith type requires a string
ramda/ramda pull request #3183
Opened 2021-09-13 15:52 UTC by trajano

The typing for memoizeWith requires the identity function to return a string.  This updates the example with the correct method

2021-09-13 21:49 UTC, CrossEye reviewed
Thank you @trajano for your contribution!

I wonder if we should consider changing the signature instead.  Because `Number` should work, as should anything for which `value.toString()` yields a unique result across your function domain.

Perhaps we can use `Key` instead of `String` with some definition of `Key` such as `String | Number | Symbol`.  What do you think?

2021-09-14 00:50 UTC, trajano commented
I don't mind, I just didn't want to touch the API/code directly.  Though personally I would rather Ramda be automatically typed no `@types/ramda` ideally.

2021-09-14 00:55 UTC, CrossEye commented
> I would rather Ramda be automatically typed no `@types/ramda` ideally.

If you're volunteering to help, we'd love it!  :smile:

The core team has little TypeScript expertise, and although we've tried to bring the typing in-house, we've made little progress.  Any help or advise you can give on this would be gratefully received!

2021-09-14 00:57 UTC, CrossEye requested changes

2021-09-14 00:57 UTC, CrossEye commented on source/memoizeWith.js
>   *
Let's change the signature instead to be more accurate.

2022-01-22 01:10 UTC, CrossEye commented
@trajano: Are you interested in pursuing this?

2022-01-22 01:10 UTC, closed without merging