feat(propIncludes): introduce propIncludes
ramda/ramda pull request #3250
Opened 2022-03-04 17:48 UTC by jaxtisapia

2022-03-06 16:06 UTC, CrossEye requested changes
I have mixed feelings about this function.  It is clearly useful on occasion.

I find a simpler example more compelling than the african/european countries ones, perhaps something like

```js
const xs = [
  {id: 1, category: 'a'}, 
  {id: 2, category: 'b'}, 
  {id: 3, category: 'a'}, 
  {id: 4, category: 'c'}, 
  {id: 5, category: 'c'}, 
  {id: 6, category: 'a'}, 
  {id: 7, category: 'd'}, 
  {id: 8, category: 'b'}, 
]

filter (propIncludes ('category') (['a', 'd'])) (xs) //=>
// [
//   {id: 1, category: 'a'}, 
//   {id: 3, category: 'a'}, 
//   {id: 6, category: 'a'}, 
//   {id: 7, category: 'd'}, 
// ]
```

The name reads badly.  Unlike, say, `subtract`, `includes` is named in a way that emphasizes partial application.  `includes (42)` is a function which accepts a list and reports whether that list includes `42`.  (`subtract (42)` by contrast is a function which accepts a value and subtracts that value from 42, to the confusion of many.)  But in this function, `propIncludes` reads to me as if it were meant to be used like this:

```js
propIncludes ('category', 42) ([foo: 'abc', category: [21, 42, 63]}) //=> true
propIncludes ('category', 42) ([foo: 'def', category: [20, 40, 60]}) //=> false
```

So if we're going to include this function, I'd like to consider alternate names.  `propIsOneOf`, `propIsIncludedIn`, `propIsIn`....

But I'm not certain if we want to include it at all.  It's simple, and well-written, but we introduced `propSatisfies` in order to capture anything beyond `propEq` and `propIs` -- and even the latter doesn't seem important enough to warrant its own function.

So, before making any of the suggested changes, can you make an argument for why this is an important enough function that we can't simply recommend, say,

```js
filter (propSatisfies (includes (__, ['a', 'd']), 'category')) (xs)
```

(which would be made better by a flipped version of `includes`, say `isOneOf`:

```js
filter (propSatisfies (isOneOf ( ['a', 'd']), 'category')) (xs)
```

?

2022-03-07 10:15 UTC, customcommander commented
This really is a well-written PR and I particularly like the efforts that went into the test cases but I have to say that I share @CrossEye observation:

```
filter (propSatisfies (includes (__, ['a', 'd']), 'category')) (xs)
```

Seems like what you're after. I think this should be an addition to the cookbook instead.

2022-03-07 10:32 UTC, jaxtisapia commented
Thanks for the review, guys.

I'll go ahead and close this PR

2022-03-07 10:32 UTC, closed without merging

2022-03-07 21:39 UTC, CrossEye commented
@jaxtisapia:

Again, thank you for participating, and please do add this function to [the Cookbook][cb]


  [cb]: https://github.com/ramda/ramda/wiki/Cookbook