Make traverse and sequence Fantasy-Land compliant
ramda/ramda pull request #3360
Opened 2023-03-27 18:36 UTC by semmel

### Motivation

- make Ramda work better with Monad libraries like [Crocks](https://crocks.dev), [Sanctuary](https://github.com/sanctuary-js/sanctuary) and [fp/ts](https://gcanti.github.io/fp-ts/)
- #3337 , #3021 , #2235

### Changes to the implementations

This changes the way `sequence` and `traverse`'s implementations delegate to the Traversable's `.traverse` (i.e. `["fantasy-land/traverse"]`) if the data type is not `Array` but an Traversable `t`:
- `traverse` expects the Traversable `t` to conform to [Fantasy Land `traverse`](https://github.com/fantasyland/fantasy-land#fantasy-landtraverse-method), thus it no longer works with "old-style" Traversables like `ramda/test/shared/Id.js` (**Breaking change**) 
- `sequence` dispatches to `f.['fantasy-land/traverse'](F, x => x)` (or `f.traverse(F, x => x)`), thus also no longer works with "old-style" Traversables.

### Changes to the interface

`traverse` and `sequence` are extended to allow a [Type Representative](https://github.com/fantasyland/fantasy-land/tree/v4.0.1#type-representatives) `F` of the inner data type (the Applicative) as first argument.  Here it can be just a plain object with a single property `"fantasy-land/of"`.

2023-03-27 19:10 UTC, kedashoe requested changes
Looks great, ty! Just some cosmetic comments

2023-03-27 19:10 UTC, kedashoe commented on dist/ramda.js
Could you revert these? We update these at release time

2023-03-27 19:10 UTC, kedashoe commented on source/sequence.js
> +  const TypeRep = { ['fantasy-land/of']: of };
Need brackets here?  `const TypeRep = { 'fantasy-land/of': of };`

2023-03-27 19:10 UTC, kedashoe commented on source/sequence.js
> +      ? traversable['fantasy-land/traverse'](TypeRep, x => x)
Same for arrow functions in source files. Could import `_identity`

2023-03-28 12:29 UTC, semmel commented
@kedashoe Thanks for the kind review! 
I tried to address your points with the latest commits.

2023-03-28 18:26 UTC, kedashoe commented
> @kedashoe Thanks for the kind review! I tried to address your points with the latest commits.

ty, looks good! I'll leave open for another day or two to allow others to comment before merging

2023-03-30 18:06 UTC, merged

2023-03-31 01:52 UTC, adispring commented
Can we release a new version? There are so many changes and bugfixes merged into master since last release. @kedashoe @CrossEye

2023-03-31 04:34 UTC, kedashoe commented
> Can we release a new version? There are so many changes and bugfixes merged into master since last release. @kedashoe @CrossEye

Been a while since I've done one. I'll give it a try this weekend.