chore: update vulnerable dependencies
ramda/ramda pull request #3420
Opened 2023-11-04 09:56 UTC by ridge-kimani

### Description
- updates components with security issues. 

Fixes #3419  

### Type of change
- [ ] Chore(non-breaking change which adds functionality)

### How Has This Been Tested?
- Update the dependencies via `npm install`
- Run all tests to ensure there's no breakage

2023-11-04 09:57 UTC, ridge-kimani commented
Updating babel also updates the build file

2023-11-06 22:41 UTC, kedashoe requested changes
ty for the PR @ridge-kimani ! A couple questions/changes.

2023-11-06 22:41 UTC, kedashoe commented on dist/ramda.js
Could you remove this file from the PR? We only update this file at release time.

2023-11-06 22:41 UTC, kedashoe commented on package.json
Looks like there are more recent versions of all these packages you've updated, does the build work with the more recent versions? Also could you include the `^` at the beginning as we do with most of our devDependencies?

2023-11-07 09:02 UTC, ridge-kimani commented on dist/ramda.js
Yeah, I will remove it. It got rebuilt once I ran the npm update.

2023-11-07 09:08 UTC, ridge-kimani commented on dist/ramda.js
When running `npm i` it creates a new build so it might have some issues if I remove it.

2023-11-07 09:10 UTC, ridge-kimani commented on package.json
Sure enough, thanks for the catch. I used to closest secure packages but with the latest ones it still works.

2023-11-07 18:22 UTC, ridge-kimani commented
Good idea @Berndy. I will audit the rest of the packages and check out if there's any breaking changes for the other packages.

2023-11-10 07:27 UTC, ridge-kimani commented
@kedashoe, I believe the `ramda.min.js` is important to be in this build because of the changes in Babel. This will make the installation process a smooth one otherwise if someone re-installs the packages it will be recompiled too.

2023-11-10 07:28 UTC, ridge-kimani reviewed
@kedashoe, I believe the ramda.min.js is important to be in this build because of the changes in Babel. This will make the installation process a smooth one otherwise if someone re-installs the packages it will be recompiled too.

2023-11-11 19:04 UTC, kedashoe requested changes
I'm seeing some errors in the tests now, could you fix those? I believe related to the sanctuary dependency update.

Also please remove `dist/ramda.js` from the commit. The files in `dist` are only updated when we cut releases. Thank you

2023-11-13 14:38 UTC, Berndy commented
I'm still getting an error when trying to run `npm run browser_test`, seemingly related to the sinon dependency. It seems we could revert that to the previous `^7.3.2` without getting any vulnerabilities back, however even then my browser_test still has a timeout issue, not sure if that's just my setup though.

Also we can still run `npm audit fix` to cut back on 16 of the remaining 22 vulnerabilities, seemingly without breaking anything further

2023-11-13 16:14 UTC, ridge-kimani commented
@Berndy Just updated it. 
RN we have `6 vulnerabilities (4 high, 2 critical)`

2023-11-15 06:27 UTC, kedashoe approved these changes
ty!

2023-11-15 06:28 UTC, merged